apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextcloud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.env }}
          envFrom:
            - secretRef:
                name: {{ include "nextcloud.fullname" . }}-env
          {{- end }}
          startupProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 12
            tcpSocket:
              port: http
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /status.php
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.volumes.www }}
            - mountPath: /var/www/html
              name: www
          {{- end }}
          {{- if .Values.volumes.config }}
            - mountPath: /var/www/html/config
              name: config
          {{- end }}
          {{- if .Values.volumes.customapps }}
            - mountPath: /var/www/html/custom_apps
              name: customapps
          {{- end }}
          {{- if .Values.volumes.data }}
            - mountPath: /var/www/html/data
              name: data
          {{- end }}
        {{- if .Values.notify_push.enabled }}
        - name: notify-push
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/var/www/html/custom_apps/notify_push/bin/x86_64/notify_push"]
          args: ["/var/www/html/config/config.php"]
          ports:
            - name: notify-push
              containerPort: {{ .Values.notify_push.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.notify_push.port }}"
            - name: NEXTCLOUD_URL
              value: "http://localhost"
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            tcpSocket:
              port: notify-push
          resources:
            {{- toYaml .Values.notify_push.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.volumes.www }}
            - mountPath: /var/www/html
              name: www
          {{- end }}
          {{- if .Values.volumes.config }}
            - mountPath: /var/www/html/config
              name: config
          {{- end }}
          {{- if .Values.volumes.customapps }}
            - mountPath: /var/www/html/custom_apps
              name: customapps
          {{- end }}
          {{- if .Values.volumes.data }}
            - mountPath: /var/www/html/data
              name: data
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.volumes.www }}
        - name: www
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.volumes.config }}
        - name: config
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.volumes.customapps }}
        - name: customapps
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.volumes.data }}
        - name: data
          {{- toYaml . | nindent 10 }}
      {{- end }}
