apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "commandcentral.fullname" . }}
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "commandcentral.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "commandcentral.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "commandcentral.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cce-http
              containerPort: 8090
              protocol: TCP
            - name: cce-https
              containerPort: 8091
              protocol: TCP
            - name: spm-http
              containerPort: 8992
              protocol: TCP
            - name: spm-https
              containerPort: 8993
              protocol: TCP
          env:
            - name: CC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "commandcentral.fullname" . }}-admin-secret
                  key: password
            - name: REPO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "commandcentral.fullname" . }}-repo-secret
                  key: username
            - name: REPO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "commandcentral.fullname" . }}-repo-secret
                  key: password
          {{- if .Values.env }}
          envFrom:
            - secretRef:
                name: {{ include "commandcentral.fullname" . }}-env
          {{- end }}
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            tcpSocket:
              port: cce-https
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            tcpSocket:
              port: cce-https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.volumes.cce.conf }}
            - mountPath: /opt/sagtools/profiles/CCE/configuration
              name: cce-conf
            {{- end }}
            {{- if .Values.volumes.cce.data }}
            - mountPath: /opt/sagtools/profiles/CCE/data
              name: cce-data
            {{- end }}
            {{- if .Values.volumes.spm.conf }}
            - mountPath: /opt/sagtools/profiles/SPM/configuration
              name: spm-conf
            {{- end }}
            {{- if .Values.volumes.spm.data }}
            - mountPath: /opt/sagtools/profiles/SPM/data
              name: spm-data
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.volumes.cce.conf }}
        - name: cce-conf
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumes.cce.data }}
        - name: cce-data
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumes.spm.conf }}
        - name: spm-conf
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumes.spm.data }}
        - name: spm-data
          {{- toYaml . | nindent 10 }}
        {{- end }}
