apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commandcentral.fullname" . }}-admin-secret
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.admin.username }}
  password: {{ .Values.secrets.admin.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commandcentral.fullname" . }}-repo-secret
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.repo.username }}
  password: {{ .Values.secrets.repo.password }}
---
{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commandcentral.fullname" . }}-env
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
{{- end }}
