apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commandcentral.fullname" . }}-admin-secret
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.admin.username }}
  password: {{ .Values.secrets.admin.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commandcentral.fullname" . }}-repo-secret
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.repo.username }}
  password: {{ .Values.secrets.repo.password }}
