apiVersion: v1
kind: Service
metadata:
  name: {{ include "commandcentral.fullname" . }}
  labels:
    {{- include "commandcentral.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.port.cce.http }}
    - port: {{ .Values.service.port.cce.http }}
      targetPort: cce-http
      protocol: TCP
      name: cce-http
    {{- end }}
    {{- if .Values.service.port.cce.https }}
    - port: {{ .Values.service.port.cce.https }}
      targetPort: cce-https
      protocol: TCP
      name: cce-https
    {{- end }}
    {{- if .Values.service.port.spm.http }}
    - port: {{ .Values.service.port.spm.http }}
      targetPort: spm-http
      protocol: TCP
      name: spm-http
    {{- end }}
    {{- if .Values.service.port.spm.https }}
    - port: {{ .Values.service.port.spm.https }}
      targetPort: spm-https
      protocol: TCP
      name: spm-https
    {{- end }}
  selector:
    {{- include "commandcentral.selectorLabels" . | nindent 4 }}
