fullnameOverride: apache

image:
  repository: ghcr.io/fab-infra/php-apache
  tag: 8.4-opensuse16-2026.08.02-0c6110a

podSecurityContext:
  runAsUser: 1003
  runAsGroup: 1004

nodeSelector:
  server-role-web: "true"
  domain-crespel-me: "true"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/default-backend: default-backend
    nginx.ingress.kubernetes.io/proxy-body-size: 300m
  hosts:
    - host: "fabien.crespel.me"
      paths:
        - path: /
          pathType: Prefix
    - host: "files.crespel.me"
      paths:
        - path: /
          pathType: Prefix
    - host: "services.crespel.me"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: apache-tls
      hosts:
        - "fabien.crespel.me"
        - "files.crespel.me"
        - "services.crespel.me"

env:
  SERVER_ENV: production
  SERVER_NAME: srv01.crespel.me
  APACHE_SERVERADMIN: webmaster@crespel.me

volumes:
  apps:
    hostPath:
      path: /home/domains/crespel.me/apps
      type: DirectoryOrCreate
  subdomains:
    hostPath:
      path: /home/domains/crespel.me/sd
      type: DirectoryOrCreate

vhosts:
  fabien.conf: |
    <VirtualHost _default_:8080>
      ServerName fabien.crespel.me
      Redirect permanent / https://www.doyoubuzz.com/fabien-crespel/
    </VirtualHost>
  files.conf: |
    <VirtualHost _default_:8080>
      ServerName files.crespel.me
      DocumentRoot /srv/www/sd/files/htdocs/
    </VirtualHost>
  services.conf: |
    <VirtualHost _default_:8080>
      ServerName services.crespel.me
      DocumentRoot /srv/www/sd/services/htdocs/
    </VirtualHost>
