fullnameOverride: backups

image:
  repository: ghcr.io/fab-infra/backuptools
  tag: opensuse16-20260607-0648-ca5d315

podSecurityContext:
  runAsUser: 1003
  runAsGroup: 1004

nodeSelector:
  server-role-web: "true"
  domain-crespel-me: "true"

schedules:
  files: "30 4 * * *"
  ldap: "0 4 * * *"
  mysql: "0 4 * * *"
  sync: "0 4 * * *"

env:
  BACKUP_BACKEND: multi
  BACKUP_BACKENDS: swift,gcs
  BACKUP_GCS_BUCKET: crespel-me-backups
  BACKUP_S3_BUCKET: crespel-me-backups
  BACKUP_S3_PROVIDER: OVH
  BACKUP_S3_REGION: rbx
  BACKUP_SYNC_BACKENDS: s3,gcs
  BACKUP_SYNC_ARGS: s3:crespel-me-nextcloud gcs:crespel-me-nextcloud --checksum
  MYSQL_HOST: mysql-slave

volumes:
  domain:
    hostPath:
      path: /home/domains/crespel.me
      type: DirectoryOrCreate
  ldap:
    hostPath:
      path: /home/domains/crespel.me/ldap
      type: DirectoryOrCreate
