fullnameOverride: ldap

image:
  repository: ghcr.io/fab-infra/openldap
  tag: 2.6-opensuse16-2026.08.02-1bf90d8

podSecurityContext:
  runAsUser: 1003
  runAsGroup: 1004

nodeSelector:
  server-role-web: "true"
  domain-crespel-me: "true"

env:
  OPENLDAP_DB_SUFFIX: dc=crespel,dc=me

secrets:
  root:
    username: cn=root,dc=crespel,dc=me

volumes:
  data:
    hostPath:
      path: /home/domains/crespel.me/ldap
      type: DirectoryOrCreate
