fullnameOverride: phpmyadmin

image:
  repository: docker.io/phpmyadmin
  tag: "5.2.3"

nodeSelector:
  server-role-web: "true"
  domain-crespel-me: "true"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/default-backend: default-backend
  hosts:
    - host: "services.crespel.me"
      paths:
        - path: /phpMyAdmin
          pathType: Prefix
  tls:
    - secretName: apache-tls
      hosts:
        - "services.crespel.me"

env:
  PMA_HOST: mysql
  PMA_PORT: 3306
  PMA_ABSOLUTE_URI: https://services.crespel.me/phpMyAdmin/

config:
  apache: |
    Alias /phpMyAdmin /var/www/html
