apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.port.http }}
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.service.port.docker }}
    - port: {{ .Values.service.port.docker }}
      targetPort: docker
      protocol: TCP
      name: docker
    {{- end }}
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
