apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "default-backend.fullname" . }}-pages
  labels:
    {{- include "default-backend.labels" . | nindent 4 }}
data:
  404.html: |
    <!DOCTYPE html>
    <html lang="fr-FR">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Page introuvable</title>
      <style type="text/css">
        * {
          margin: 0;
          padding: 0;
          border: 0;
        }
        body {
          padding: 0 10px;
          font-family: Verdana, Arial, Helvetica, sans-serif;
          font-size: 10pt;
          background-color: #333333;
          color: #cccccc;
          text-align: center;
        }
        h1 {
          margin: 20px 10px;
          font-size: 22pt;
          color: #dddddd;
          text-shadow: 0 0 5px black;
        }
        p {
          margin-bottom: 10px;
        }
      </style>
    </head>
    <body>
      <h1>Page introuvable</h1>
      <p>La page &agrave; laquelle vous tentez d'acc&eacute;der n'existe pas ou plus.</p>
      <p style="margin-top: 40px;"><img src="https://upload.wikimedia.org/wikipedia/commons/0/0d/Tumbeasts_sign1.png" style="max-width: 100%; max-height: 400px;" title="Tumbeasts by Matthew Inman" /></p>
    </body>
    </html>
  503.html: |
    <!DOCTYPE html>
    <html lang="fr-FR">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Service indisponible</title>
      <style type="text/css">
        * {
          margin: 0;
          padding: 0;
          border: 0;
        }
        body {
          padding: 0 10px;
          font-family: Verdana, Arial, Helvetica, sans-serif;
          font-size: 10pt;
          background-color: #333333;
          color: #cccccc;
          text-align: center;
        }
        h1 {
          margin: 20px 10px;
          font-size: 22pt;
          color: #dddddd;
          text-shadow: 0 0 5px black;
        }
        p {
          margin-bottom: 10px;
        }
      </style>
    </head>
    <body>
      <h1>Service indisponible</h1>
      <p>Ce site est temporairement indisponible en raison d'un incident technique ou d'une op&eacute;ration de maintenance.</p>
      <p>Merci de renouveler votre tentative ult&eacute;rieurement.</p>
      <p style="margin-top: 40px;"><img src="https://upload.wikimedia.org/wikipedia/commons/8/8c/Tumbeasts_servers.png" style="max-width: 100%; max-height: 400px;" title="Tumbeasts by Matthew Inman" /></p>
    </body>
    </html>
